apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prometheus
      version: '15.8.7'
  values:
    serviceAccounts:
      server:
        name: amp-iamproxy-ingest-service-account
        annotations: 
          eks.amazonaws.com/role-arn: arn:aws:iam::482649550366:role/amp-iamproxy-ingest-role
    server:
      remoteWrite:
      - url: https://aps-workspaces.eu-west-1.amazonaws.com/workspaces/ws-5bc96ac2-938d-4b25-8e18-c38d1a1be8a8/api/v1/remote_write
        sigv4:
          region: eu-west-1     
        queue_config:
          max_samples_per_send: 1000
          max_shards: 200
          capacity: 2500
  interval: 1m0s
