---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: webapp
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        spec:
          replicas: 1        
      target:
        kind: Deployment
    - patch: |
        apiVersion: autoscaling/v1
        kind: HorizontalPodAutoscaler
        spec:
          maxReplicas: 1
          minReplicas: 1       
      target:
        kind: HorizontalPodAutoscaler